### ISSUE TITLE
Script no longer works due to login changes for Garmin Connect

### ISSUE THREAD

**Issue by flowstatedev** [flowstatedev/gc-private#1]
Need to merge latest login code from: https://github.com/pe-st/garmin-connect-export

**Comment by zeair** [comment]
when do you think you will be able to fix this ?

**Comment by flowstatedev** [comment]
@zeair thanks for the interest in the script. The issue is fixed now.

**Comment by flowstatedev** [comment]
Fixed by merging latest login code from https://github.com/pe-st/garmin-connect-export

**Comment by zeair** [comment]
Works, thanks!
